#include "submitwindow.h"
#include "ui_submitwindow.h"
#include "submit.h"
#include <iostream>
/* parameterized constructor grenerated by qt creator
 * takes a parent window
 * modified to take a name string
 */
SubmitWindow::SubmitWindow(std::string json_str, QWidget *parent) :
                           QDialog(parent), ui(new Ui::SubmitWindow),
                           json_str(json_str) {
  ui->setupUi(this);
  ui->password_val->setEchoMode(QLineEdit::Password);
  ui->submitButton->setEnabled(true);
}
/* destructor generated by qt */
SubmitWindow::~SubmitWindow() {
    delete ui;
}

/* cancel button clicked event closed this window and whole application */
void SubmitWindow::on_cancelButton_clicked() {
    this->close();
}

/* submit button appends results to a name string and opens a tcp socket
   directly based on example from libcurl
*/

void SubmitWindow::on_submitButton_clicked() {
  submit sub;
  sub.do_submission( ui->username_val->text().toStdString(), ui->password_val->text().toStdString(), json_str);
  std::string res = sub.getError();
  /* Check for errors */
  if(res != "") {
    ui->responseLabel->setText(QString(res.c_str())); //QString doesnt have a std::string constructor
  } else {
    std::string response = sub.getResponse();
    if(response == "200 OK") {
      /* always cleanup */
      ui->submitButton->setEnabled(false);
      sub.cleanup();
      this->close();
    } else {
      ui->responseLabel->setText(QString(response.c_str()));
    }
  }
}

